### ISSUE TITLE
--gpu 1  throw an error ,  code  can't run on  the GPU

### ISSUE THREAD

**Issue by showaichuan** [hvy/chainer-visualization#2]
hi, I  use the command  blew like what  the read.md say,
`python visualize.py --image-filename images/cat.jpg --model-filename VGG.model --out-dirname results --gpu 0`
 it's well to run the whole code.

but when I set the GPU param to 1 , it throws an error:

```

Traceback (most recent call last):
  File "visualize.py", line 145, in <module>
    main(args)
  File "visualize.py", line 135, in main
    cuda.get_device(args.gpu).use()
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 219, in get_device
    return _get_device(*args)
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 225, in _get_device
    check_cuda_available()
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 87, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).'module' object has no attribute '_clip'
```
my  gpu  is  1080 , cuda is 8.0, cudnn is 5.0 , chainer is  1.24.0, may  be it's  the gpu resaon, the code may not insist the gpu

**Comment by hvy** [comment]
It seems like Chainer isn't correctly installed with CUDA. Did you set the env variables according to https://github.com/pfnet/chainer#installation before installing Chainer (eg. using pip)?

**Comment by 08291025** [comment]
Hello, when I used the  command blew like what the read.md say
python visualize.py --image-filename images/cat.jpg --model-filename VGG.model --out-dirname results --gpu 0
 it throws an error:

Traceback (most recent call last):
  File "visualize.py", line 145, in <module>
    main(args)
  File "visualize.py", line 131, in main
    model = VGG()
  File "/home/wang/chainer-visualization-master/lib/models/vgg.py", line 42, in __init__
    self.mps = [F.MaxPooling2D(2, 2, use_cudnn=False) for _ in self.conv_blocks]
  File "/home/wang/chainer-visualization-master/lib/models/vgg.py", line 42, in <listcomp>
    self.mps = [F.MaxPooling2D(2, 2, use_cudnn=False) for _ in self.conv_blocks]
TypeError: __init__() got an unexpected keyword argument 'use_cudnn'

I have successfully installed cuda and cudnn, where is the problem?

**Comment by hvy** [comment]
Hi,

Which version of Chainer are you using? The `use_cudnn` argument has been removed from `MaxPooling2D` since v2 and the code is currently written for v1. I'll add a reference link, it should be easy to fix.

http://docs.chainer.org/en/stable/upgrade.html?highlight=use_cudnn#configurations-are-added-and-replace-some-of-existing-global-flags

Thanks for the heads up.

**Comment by 08291025** [comment]
I am using the V2 version, can you share a V2 version of vgg.py? Thank you!

**Comment by hvy** [comment]
Sorry for the delayed reply.

I am slightly busy at the moment with university. I'd be more than happy to merge a pull request but else, please let me fix it in a few weeks.

**Comment by 08291025** [comment]
OK, thank you very much！

**Comment by hvy** [comment]
@08291025 I have updated the code to run on Chainer v3.0 so this issue should be fixed. Let me close this one :)
